Feat git ref include branch
deltachat/deltachat-desktop pull request #2043
Opened 2021-01-12 00:20 UTC by Jikstra

2021-01-12 08:11 UTC, Simon-Laux approved these changes

2021-01-12 08:12 UTC, Simon-Laux commented on bin/build-shared-version-info.js
> +  if (status !== 0) throw new Err(stderr)
```suggestion
  if (status !== 0) throw new Error(stderr)
```

2021-01-12 08:16 UTC, Simon-Laux requested changes
Looks like we need to investigate why the ci doesn't like it first:
```
Error: fatal: ref HEAD is not a symbolic ref

    at gatherProcessStdout (/home/runner/work/deltachat-desktop/deltachat-desktop/bin/build-shared-version-info.js:7:27)
    at gatherBuildInfo (/home/runner/work/deltachat-desktop/deltachat-desktop/bin/build-shared-version-info.js:15:18)
    at Object.<anonymous> (/home/runner/work/deltachat-desktop/deltachat-desktop/bin/build-shared-version-info.js:34:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```
Maybe we can try a second strategy if getting the branch this way fails, like fetching the branch from github ci vars.

2021-01-13 05:57 UTC, Jikstra commented
Are we on the ci probably shallow cloning the branch for quicker checkouts? If I remember it correctly it fetches only the latest commit without the history. Probably this causes problems.

2021-02-11 11:40 UTC, merged