Some changes/improvements to german translation
deltachat/deltachat-desktop pull request #2330
Opened 2021-08-07 16:13 UTC by porky11

2021-08-07 18:50 UTC, Jikstra commented
Thank you, very appreciated!
Probably we need to push the to deltachat-android, so that they get synced with transifex. @r10s how is the current situation with translations?

2021-08-08 20:15 UTC, r10s commented
> Probably we need to push the to deltachat-android, so that they get synced with transifex. @r10s how is the current situation with translations?

no need to push to android, translations but english needs to be changed on transifex, you can login with your github account there, see https://delta.chat/en/contribute#translations-and-bug-reports

for the other suggestions, cc @Yettte

2021-08-08 21:59 UTC, dotlambda commented
> to the changes: afaik, the hyphen is not needed for "Delta Chat" unless it is an compound word, so, "Delta Chat" but "Delta-Chat-App", not sure, though.

I would say "Delta Chat-App".

2021-08-09 09:29 UTC, r10s commented
> I would say "Delta Chat-App".

hm, that's probably not so fortunate as that glues togehter "Chat-App", leaving "Delta" alone, in general, that seems not to be the goal of the hyphen in german, cmp. https://www.duden.de/sprachwissen/rechtschreibregeln/bindestrich

that in mind, the current spelling "Delta Chat App" seems to be just fine, see examples at https://de.wikipedia.org/wiki/Durchkopplung#Eigennamen_von_Institutionen

anyway, i suggest to close this pr as it is not actionable here.

2021-08-09 09:39 UTC, r10s requested changes
i applied the typo fixes to transifex - thanks a lot for taking care, @porky11. the changes will apply to all apps on the next pull of translations then.

as said above, i suggest to close this as there is no actionable item left here. of course, discussion can continue.

2021-08-09 09:39 UTC, r10s commented on _locales/de.xml
> +    <string name="media_preview">Medien-Vorschau</string>
i applied this change to transifex.

2021-08-09 09:39 UTC, r10s commented on _locales/de.xml
> +    <string name="login_error_cannot_login">Login als \"%1$s\" nicht möglich. Bitte E-Mail-Adresse und Passwort auf Richtigkeit überprüfen.</string>
i applied this change to transifex.

2021-08-09 09:39 UTC, r10s commented on _locales/de.xml
> +    <string name="pref_screen_security_explain">Aufforderung zum Sperren von Screenshots in der kürzlich erstellten Liste und in der App</string>
i applied this change to transifex.

2021-08-09 09:39 UTC, r10s commented on _locales/de.xml
> +    <string name="pref_in_chat_sounds">In-Chat-Klänge</string>
i applied this change to transifex.

2021-08-09 09:40 UTC, closed without merging