Prepare for v1.30.0
deltachat/deltachat-desktop pull request #2734
Opened 2022-05-05 13:00 UTC by Jikstra

2022-05-05 18:06 UTC, Simon-Laux requested changes
shouldn't we do an 1.29 ('cause its an testrelease?) first and bump it on release to 1.30?

2022-05-05 18:30 UTC, dotlambda requested changes

2022-05-05 18:30 UTC, dotlambda commented on package-lock.json
> +      "version": "1.29.2",
```suggestion
      "version": "1.29.0",
```

2022-05-06 13:54 UTC, merged

2022-05-06 15:55 UTC, dotlambda commented on package-lock.json
> +      "version": "1.29.2",
This is still wrong