Proper description for Linux packages
deltachat/deltachat-desktop pull request #3317
Opened 2023-07-19 14:24 UTC by farooqkz

Fixes #3209

2023-07-19 20:48 UTC, Simon-Laux approved these changes

2023-07-19 20:50 UTC, Simon-Laux commented
maybe also wait for ads review? but might be ok to merge if you tested it already with the GUI program that had the problem. 🤷

2023-07-21 13:05 UTC, adbenitez commented
how do I download the .deb generated by this PR? IIRC they used to be ready for download clicking "details" but that doesn't seem to work

2023-07-21 13:21 UTC, Simon-Laux commented on electron-builder.json5
> +    description: 'The Email messenger\nWith Delta Chat, you can use your existing Email account as a messenger. End-to-End Encryption with Autocrypt is supported and you can have interactive chat exp
nope this is not right place for it, look at the first line, this file is auto generated

2023-07-21 13:23 UTC, Simon-Laux requested changes
cool that you found this fix, but it will not persist as you added it to an autogenerated file. you need to add it to `build/gen-electron-builder-config.js` instead and then run `npm run pack:generate_config` to update this autogenerated file

2023-07-22 08:00 UTC, farooqkz commented
@adbenitez @Simon-Laux Yep I am strong with the Source :D

2023-07-22 10:04 UTC, Simon-Laux approved these changes

2023-07-22 10:04 UTC, merged