add keyboard shortcut to close child windows and add a custom menu to the child windows
deltachat/deltachat-desktop pull request #3770
Opened 2024-04-12 18:45 UTC by Simon-Laux

closes #3510

2024-04-14 13:51 UTC, WofWca requested changes
I'd DRY or add a comment that it's copy-pasted so that whoever changes the code in the future doesn't forget to change all 3 places. But it's not critical I guess, unlike the `win` vs `window` comment.

2024-04-14 13:51 UTC, WofWca commented on src/main/windows/help.ts
> +      // change to webxdc menu
Not "webxdc"

2024-04-14 13:51 UTC, WofWca commented on src/main/windows/help.ts
> +              window.close()
```suggestion
              win.close()
```

2024-04-14 15:53 UTC, Simon-Laux commented on src/main/windows/help.ts
> +      // change to webxdc menu
```suggestion
      // change to help menu
```

2024-04-16 17:15 UTC, WofWca approved these changes
Not a big expert on menus, but it works.

2024-04-16 17:15 UTC, WofWca commented on src/main/windows/html_email.ts
> +      // change to webxdc menu
```suggestion
      // change to email menu
```

2024-04-16 17:18 UTC, merged