Ctrl+Q closes app
deltachat/deltachat-desktop pull request #4107
Opened 2024-09-05 13:31 UTC by maxphilippov

- handle ctrl+q when main window is focused to properly close the app

- #4084 tested on Windows, need further testing

2024-09-05 17:21 UTC, meganoahj approved these changes
Works on SteamOS (immutable Arch) with latest main branch
edit: it only minimizes

2024-09-05 20:41 UTC, nicodh commented
> Works on SteamOS (immutable Arch) with latest main branch edit: it only minimizes

If it only minimzes it does not work besćause this PR aims to really close the app, not only minimizes it

2024-09-06 05:06 UTC, maxphilippov commented
> Works on SteamOS (immutable Arch) with latest main branch
Sorry, what do you mean by the latest main branch?
On main it minimizes, on this branch it should completely close the app. Does it minimize for you on this branch?

2024-09-08 16:27 UTC, nicodh requested changes
There is a irritating warning on console, which should be an info only, since the message coming from backend can't be send to already destroyed window which is expected behaviour.
https://github.com/deltachat/deltachat-desktop/blob/main/src/main/windows/main.ts#L238

So maybe change console.warn to console.info

2024-09-08 23:20 UTC, Simon-Laux approved these changes
code LGTM, didn't test

2024-09-08 23:44 UTC, Simon-Laux commented on CHANGELOG.md
> +- Ctrl/Cmd+Q (also File->Quit) now should properly close the app when focus is on main window
no it is the pr number that we but here

2024-09-09 13:18 UTC, nicodh approved these changes

2024-09-09 13:23 UTC, merged

2024-09-09 19:51 UTC, missytake commented on CHANGELOG.md
> +- Ctrl/Cmd+Q (also File->Quit) now should properly close the app when focus is on main window
Either way, it's still missing?