Add block contact and encryption info to profile
deltachat/deltachat-desktop pull request #4147
Opened 2024-09-25 09:25 UTC by maxphilippov

- new `useViewProfileMenu` menu with two items: Block/Unblock Contact and Encryption Info
- minor refactor of `useChatDialog`, so we don't have to have a ChatListItem to block contact or get EncryptionInfo
- resolves #4043

2024-09-26 04:15 UTC, nicodh requested changes
There are 3 options to block a contact now:
1. from contact context menu in chat list
2. from context menu in chat view
3. from settings menu in ViewProfile

Depending on the use case the behaviour is different:
1. if you use option 1 while the chat is not open, everything is fine
2. if you use option 1 while the chat is open, the chat stays open
3. if you use option 2 while the chat is open, the chat is unselected and closed
4. if you use option 3 while the chat is open, the ViewProfile stays open, the chat disappears from chat list, but the chat is still open when you close the ViewProfile dialog
5. in an open chat (remained after blocking a contact) the context menu still shows: "Block contact" instead of "unblock contact"

I suggest to always use the same behaviour as in  chat views context menu, that means after blocking a contact the current chat should be unselected if it is the 1:1 chat with the blocked user. If the user is blocked from "ViewProfile" dialog the dialog should be closed too. Otherwise we would have to add a flag to show that a user is blocked.

2024-09-26 17:52 UTC, maxphilippov commented
> 5. in an open chat (remained after blocking a contact) the context menu still shows: "Block contact" instead of "unblock contact"
There's a separate issue #4046 for this and from what I saw looking at this it seems more like a chatlist problem so I don't want to mix it up here, unless it's a minor fix, I'll push it as a separate PR.

Thanks for other points! I'll reiterate on that (+ menu styling) and push an update soon

2024-10-03 15:09 UTC, nicodh commented
> Thanks for other points! I'll reiterate on that (+ menu styling) and push an update soon

@maxphilippov please let me know when you updated this

2024-10-08 09:13 UTC, maxphilippov commented
@nicodh everything is ready for review. I've also moved "Edit Name" to this new menu as we discussed with @r10s. There also rises a question if we need the same menu for groups but with only "Encryption Info" + "Edit Name" but that's for another PR probably.

2024-10-09 13:22 UTC, nicodh approved these changes

2024-10-09 13:40 UTC, r10s commented
> There also rises a question if we need the same menu for groups but with only "Encryption Info" + "Edit Name" but that's for another PR probably.

for groups, editing name+image is far more important than setting a nickname, so i would not suggest to move that to the "three dot menu" without other changes (eg. being able to access "Edit" also from enlarged avatar view as on android).

still, for encryption info, the three dot menu makes sense for groups, so that this is consistent.

when we have that consistent, also in another PR, we can probably also remove  "Encryption Info" from the chatlist's context menus. 

however, that is future and shall not block merging this PR :) all in all a nice improvement, thanks a lot.

2024-10-09 15:08 UTC, merged